### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by rdutta** [melkypie/resource-packs#305]
On launching runelite I am getting an npe

```java
[Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
        at melky.resourcepacks.ResourcePacksManager.saveClientSprites(ResourcePacksManager.java:428)
        at melky.resourcepacks.ResourcePacksManager.updateAllOverrides(ResourcePacksManager.java:375)
        at melky.resourcepacks.ResourcePacksPlugin.lambda$queueUpdateAllOverrides$5(ResourcePacksPlugin.java:318)
```

**Comment by raiyni** [comment]
This implies config manager doesn't exist. Which means there is an error further up in the chain. Can you provide your full log? Can you reproduce it?

**Comment by rdutta** [comment]
Here is the full log.

```java
[main] INFO  net.runelite.client.RuneLite - RuneLite 1.10.38-SNAPSHOT (launcher version unknown) starting up, args: --developer-mode
[main] INFO  net.runelite.client.RuneLite - Java VM arguments: -ea -Drunelite.pluginhub.version=1.10.37
[Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
[Preloader] INFO  net.runelite.client.rs.ClientLoader - injected-client 10815979517.255
[main] INFO  injected-client - read 5 credentials from disk
[main] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: false, active: true, id: ##############)
[main] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: true, active: false, id: 0)
[main] INFO  n.r.client.config.ConfigManager - Profile '$rsprofile' is up to date
[main] INFO  n.r.client.config.ConfigManager - Using profile: default (##############))
[main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
[main] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" jar "6Z8kMqYayqblo1rBfU3SLOCPgZOqo2vh4RB_qGizo2g"
[main] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
[main] INFO  net.runelite.client.RuneLite - Client initialization took 6459ms. Uptime: 7426ms
[Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
        at melky.resourcepacks.ResourcePacksManager.saveClientSprites(ResourcePacksManager.java:428)
        at melky.resourcepacks.ResourcePacksManager.updateAllOverrides(ResourcePacksManager.java:375)
        at melky.resourcepacks.ResourcePacksPlugin.lambda$queueUpdateAllOverrides$5(ResourcePacksPlugin.java:318)
        at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
        at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
        at client.la(client.java:11182)
        at client.bj(client.java)
        at ba.ov(ba.java:409)
        at ba.hi(ba.java)
        at ba.run(ba.java:5071)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by raiyni** [comment]
I see you are building your own runelite. I'd be interested if you can reproduce this on release.

**Comment by rdutta** [comment]
Same error:

```java
[RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.10.37 (launcher version 2.6.10)
...
[Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at melky.resourcepacks.ResourcePacksManager.saveClientSprites(ResourcePacksManager.java:428)
	at melky.resourcepacks.ResourcePacksManager.updateAllOverrides(ResourcePacksManager.java:375)
	at melky.resourcepacks.ResourcePacksPlugin.lambda$queueUpdateAllOverrides$5(ResourcePacksPlugin.java:318)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.la(client.java:11182)
	at client.bj(client.java)
	at ba.ov(ba.java:409)
	at ba.hi(ba.java)
	at ba.run(ba.java:5071)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by raiyni** [comment]
I'm not seeing this with a fresh profile. Have you made any modification to the interface styles  plugin or turned it on but not changed any config values?

**Comment by rdutta** [comment]
> I'm not seeing this with a fresh profile. Have you made any modification to the interface styles plugin config or turned it on but not changed any config values?

Toggling the Interface Styles plugin seems to have done something and I'm no longer getting the error.
